namespace DWH.Domain {
    public class LoadCarDetail : Entity {
        public string Title { get; set; }
        public string OfferSeek { get; set; }
        public string PrivateBusiness { get; set; }
        public string Category { get; set; }
        public string Region { get; set; }
        public string Subregion { get; set; }
        public string UserId { get; set; }
        public string City { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string EngineCode { get; set; }
        public string Version { get; set; }
        public string Year { get; set; }
        public int Mileage { get; set; }
        public string EngineCapacity { get; set; }
        public string Vin { get; set; }
        public string FuelType { get; set; }
        public string EnginePower { get; set; }
        public string Gearbox { get; set; }
        public string Transmission { get; set; }
        public string BodyType { get; set; }
        public string DoorCount { get; set; }
        public string NrSeats { get; set; }
        public string Color { get; set; }
        public string Price { get; set; }
        public double PriceRaw { get; set; }
        public string CountryOrigin { get; set; }
        public string Registration { get; set; }
        public int UserStatus { get; set; }
        public string Env { get; set; }

        //FEATURES
        public bool Abs { get; set; }
        public bool Cd { get; set; }
        public bool CentralLock { get; set; }
        public bool FrontElectricWindows { get; set; }
        public bool ElectronicRearviewMirrors { get; set; }
        public bool ElectronicImmobiliser { get; set; }
        public bool FrontAirbags { get; set; }
        public bool FrontPassengerAirbags { get; set; }
        public bool OriginalRadio { get; set; }
        public bool AssistedSteering { get; set; }
        public bool Alarm { get; set; }
        public bool AlloyWheels { get; set; }
        public bool Asr { get; set; }
        public bool ParkAssist { get; set; }
        public bool LaneAssist { get; set; }
        public bool Bluetooth { get; set; }
        public bool AutomaticWipers { get; set; }
        public bool BlindSpotSensor { get; set; }
        public bool AutomaticLights { get; set; }
        public bool BothParkingSensors { get; set; }
        public bool RearParkingSensors { get; set; }
        public bool PanoramicSunroof { get; set; }
        public bool ElectricExteriorMirror { get; set; }
        public bool ElectricInteriorMirror { get; set; }
        public bool RearElectricWindows { get; set; }
        public bool ElectricAdjustableSeats { get; set; }
        public bool Esp { get; set; }
        public bool AuxIn { get; set; }
        public bool SdSocket { get; set; }
        public bool UsbSocket { get; set; }
        public bool TowingHook { get; set; }
        public bool HeadDisplay { get; set; }
        public bool Isofix { get; set; }
        public bool RearviewCamera { get; set; }
        public bool AutomaticAirConditioning { get; set; }
        public bool QuadAirConditioning { get; set; }
        public bool DualAirConditioning { get; set; }
        public bool OnboardComputer { get; set; }
        public bool SideWindowAirbags { get; set; }
        public bool ShiftPaddles { get; set; }
        public bool Mp3 { get; set; }
        public bool Gps { get; set; }
        public bool Dvd { get; set; }
        public bool SpeedLimiter { get; set; }
        public bool HeatedWindshield { get; set; }
        public bool AuxiliaryHeating { get; set; }
        public bool HeatedRearviewMirrors { get; set; }
        public bool DriverKneeAirbag { get; set; }
        public bool FrontSideAirbags { get; set; }
        public bool RearPassengerAirbags { get; set; }
        public bool TintedWindows { get; set; }
        public bool RoofBars { get; set; }
        public bool Sunroof { get; set; }
        public bool DaytimeLights { get; set; }
        public bool SystemStartStop { get; set; }
        public bool Leds { get; set; }
        public bool FogLights { get; set; }
        public bool XenonLights { get; set; }
        public bool LeatherInterior { get; set; }
        public bool VelourInterior { get; set; }
        public bool CruiseControl { get; set; }
        public bool SteeringWhellComands { get; set; }
        public bool CdChanger { get; set; }
    }
}
