// <auto-generated />
using System;
using HurtowniaDanych.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HurtowniaDanych.Storage.Migrations
{
    [DbContext(typeof(DataWarehouseContext))]
    [Migration("20181129211751_HDProjectMigration")]
    partial class HDProjectMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HurtowniaDanych.Advertisement.Models.Details", b =>
                {
                    b.Property<long>("AdId");

                    b.Property<string>("BodyType");

                    b.Property<string>("Category");

                    b.Property<string>("City");

                    b.Property<string>("Color");

                    b.Property<string>("CountryOrigin");

                    b.Property<string>("DoorCount");

                    b.Property<string>("EngineCapacity");

                    b.Property<string>("EngineCode");

                    b.Property<string>("EnginePower");

                    b.Property<string>("Env");

                    b.Property<string>("FuelType");

                    b.Property<string>("Gearbox");

                    b.Property<DateTime>("Inserted");

                    b.Property<string>("Make");

                    b.Property<int>("Mileage");

                    b.Property<string>("Model");

                    b.Property<string>("NrSeats");

                    b.Property<string>("OfferSeek");

                    b.Property<string>("Price");

                    b.Property<string>("PriceRaw");

                    b.Property<string>("PrivateBusiness");

                    b.Property<string>("Region");

                    b.Property<string>("Registration");

                    b.Property<string>("Subregion");

                    b.Property<string>("Title");

                    b.Property<string>("Transmission");

                    b.Property<string>("UserId");

                    b.Property<int>("UserStatus");

                    b.Property<string>("Version");

                    b.Property<string>("Vin");

                    b.Property<string>("Year");

                    b.HasKey("AdId");

                    b.ToTable("CarDetails");
                });

            modelBuilder.Entity("HurtowniaDanych.Advertisement.Models.Features", b =>
                {
                    b.Property<long>("AdvertId");

                    b.Property<bool>("Abs");

                    b.Property<bool>("Alarm");

                    b.Property<bool>("AlloyWheels");

                    b.Property<bool>("Asr");

                    b.Property<bool>("AssistedSteering");

                    b.Property<bool>("AutomaticAirConditioning");

                    b.Property<bool>("AutomaticLights");

                    b.Property<bool>("AutomaticWipers");

                    b.Property<bool>("AuxIn");

                    b.Property<bool>("AuxiliaryHeating");

                    b.Property<bool>("BlindSpotSensor");

                    b.Property<bool>("Bluetooth");

                    b.Property<bool>("BothParkingSensors");

                    b.Property<bool>("Cd");

                    b.Property<bool>("CdChanger");

                    b.Property<bool>("CentralLock");

                    b.Property<bool>("CruiseControl");

                    b.Property<bool>("DaytimeLights");

                    b.Property<bool>("DriverKneeAirbag");

                    b.Property<bool>("DualAirConditioning");

                    b.Property<bool>("Dvd");

                    b.Property<bool>("ElectricAdjustableSeats");

                    b.Property<bool>("ElectricExteriorMirror");

                    b.Property<bool>("ElectricInteriorMirror");

                    b.Property<bool>("ElectronicImmobiliser");

                    b.Property<bool>("ElectronicRearviewMirrors");

                    b.Property<bool>("Esp");

                    b.Property<bool>("FogLights");

                    b.Property<bool>("FrontAirbags");

                    b.Property<bool>("FrontElectricWindows");

                    b.Property<bool>("FrontPassengerAirbags");

                    b.Property<bool>("FrontSideAirbags");

                    b.Property<bool>("Gps");

                    b.Property<bool>("HeadDisplay");

                    b.Property<bool>("HeatedRearviewMirrors");

                    b.Property<bool>("HeatedWindshield");

                    b.Property<DateTime>("Inserted");

                    b.Property<bool>("Isofix");

                    b.Property<bool>("LaneAssist");

                    b.Property<bool>("LeatherInterior");

                    b.Property<bool>("Leds");

                    b.Property<bool>("Mp3");

                    b.Property<bool>("OnboardComputer");

                    b.Property<bool>("OriginalRadio");

                    b.Property<bool>("PanoramicSunroof");

                    b.Property<bool>("ParkAssist");

                    b.Property<bool>("QuadAirConditioning");

                    b.Property<bool>("RearElectricWindows");

                    b.Property<bool>("RearParkingSensors");

                    b.Property<bool>("RearPassengerAirbags");

                    b.Property<bool>("RearviewCamera");

                    b.Property<bool>("RoofBars");

                    b.Property<bool>("SdSocket");

                    b.Property<bool>("ShiftPaddles");

                    b.Property<bool>("SideWindowAirbags");

                    b.Property<bool>("SpeedLimiter");

                    b.Property<bool>("SteeringWhellComands");

                    b.Property<bool>("Sunroof");

                    b.Property<bool>("SystemStartStop");

                    b.Property<bool>("TintedWindows");

                    b.Property<bool>("TowingHook");

                    b.Property<bool>("UsbSocket");

                    b.Property<bool>("VelourInterior");

                    b.Property<bool>("XenonLights");

                    b.HasKey("AdvertId");

                    b.ToTable("CarFeatures");
                });

            modelBuilder.Entity("HurtowniaDanych.Advertisement.Models.Mileages", b =>
                {
                    b.Property<long>("AdId");

                    b.Property<string>("Type");

                    b.Property<string>("UnitCode");

                    b.Property<string>("Value");

                    b.HasKey("AdId");

                    b.ToTable("CarSchema");
                });

            modelBuilder.Entity("HurtowniaDanych.Advertisement.Models.Offers", b =>
                {
                    b.Property<long>("AdId");

                    b.Property<string>("Price");

                    b.Property<string>("PriceCurrency");

                    b.Property<string>("Type")
                        .HasColumnName("Offers_Type");

                    b.HasKey("AdId");

                    b.ToTable("CarSchema");
                });

            modelBuilder.Entity("HurtowniaDanych.Advertisement.Models.Schema", b =>
                {
                    b.Property<long>("AdId");

                    b.Property<string>("BodyType");

                    b.Property<string>("Brand");

                    b.Property<string>("Color");

                    b.Property<string>("Context");

                    b.Property<string>("DateVehicleFirstRegistered");

                    b.Property<string>("Description");

                    b.Property<string>("FuelType");

                    b.Property<DateTime>("Inserted");

                    b.Property<string>("ItemCondition");

                    b.Property<string>("Model");

                    b.Property<string>("Name");

                    b.Property<int?>("NumberOfDoors");

                    b.Property<string>("Type")
                        .HasColumnName("Schema_Type");

                    b.Property<string>("Url");

                    b.Property<string>("VehicleIdentificationNumber");

                    b.Property<string>("VehicleSeatingCapacity");

                    b.HasKey("AdId");

                    b.ToTable("CarSchema");
                });

            modelBuilder.Entity("HurtowniaDanych.Advertisement.Models.VehicleEng", b =>
                {
                    b.Property<long>("AdId");

                    b.Property<string>("EngineDisplacement");

                    b.Property<string>("Type")
                        .HasColumnName("VehicleEng_Type");

                    b.HasKey("AdId");

                    b.ToTable("CarSchema");
                });

            modelBuilder.Entity("HurtowniaDanych.Advertisement.Models.Mileages", b =>
                {
                    b.HasOne("HurtowniaDanych.Advertisement.Models.Schema", "Schema")
                        .WithOne("MileageFromOdometer")
                        .HasForeignKey("HurtowniaDanych.Advertisement.Models.Mileages", "AdId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HurtowniaDanych.Advertisement.Models.Offers", b =>
                {
                    b.HasOne("HurtowniaDanych.Advertisement.Models.Schema", "Schema")
                        .WithOne("Offers")
                        .HasForeignKey("HurtowniaDanych.Advertisement.Models.Offers", "AdId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HurtowniaDanych.Advertisement.Models.VehicleEng", b =>
                {
                    b.HasOne("HurtowniaDanych.Advertisement.Models.Schema", "Schema")
                        .WithOne("VehicleEngine")
                        .HasForeignKey("HurtowniaDanych.Advertisement.Models.VehicleEng", "AdId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
