// <auto-generated />
using System;
using HurtowniaDanych.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HurtowniaDanych.Storage.Migrations
{
    [DbContext(typeof(DataWarehouseContext))]
    partial class DataWarehouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HurtowaniaDanych.Domain.CarTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("ABS");

                    b.Property<bool>("AUX");

                    b.Property<bool>("ActiveCruiseControl");

                    b.Property<string>("AddDate");

                    b.Property<bool>("AdjustableSuspension");

                    b.Property<bool>("AirConditioningAutomatic");

                    b.Property<bool>("AirConditioningFourZone");

                    b.Property<bool>("AirConditioningManual");

                    b.Property<bool>("AirConditioningTwoZone");

                    b.Property<bool>("AirCurtains");

                    b.Property<bool>("Alarm");

                    b.Property<bool>("AlloyWheels");

                    b.Property<bool>("AntiFogLights");

                    b.Property<bool>("Bluetooth");

                    b.Property<string>("BodyType");

                    b.Property<string>("Brand");

                    b.Property<bool>("CD");

                    b.Property<bool>("CDChanger");

                    b.Property<string>("Category");

                    b.Property<bool>("CentralLock");

                    b.Property<string>("City");

                    b.Property<string>("Color");

                    b.Property<string>("Cost");

                    b.Property<string>("Country");

                    b.Property<bool>("CruiseControl");

                    b.Property<bool>("DVD");

                    b.Property<bool>("DaytimeLights");

                    b.Property<bool>("DeadZoneSensor");

                    b.Property<string>("Description");

                    b.Property<int>("DoorsCount");

                    b.Property<bool>("DriverAirbag");

                    b.Property<bool>("ESP");

                    b.Property<bool>("ElectricFrontWindows");

                    b.Property<bool>("ElectricRearMirror");

                    b.Property<bool>("ElectricRearWindows");

                    b.Property<bool>("ElectricSideMirros");

                    b.Property<bool>("ElectricallyAdjustableSeats");

                    b.Property<int>("EngineDisplacement");

                    b.Property<bool>("FactoryRadio");

                    b.Property<string>("FirstRegistration");

                    b.Property<bool>("FrontParkingSensors");

                    b.Property<bool>("FrontSideAirbags");

                    b.Property<string>("Fueltype");

                    b.Property<bool>("GPS");

                    b.Property<bool>("HUD");

                    b.Property<bool>("HeatedFrontMirror");

                    b.Property<bool>("HeatedFrontSeats");

                    b.Property<bool>("HeatedRearSeats");

                    b.Property<bool>("HeatedSiteMirrors");

                    b.Property<bool>("Hook");

                    b.Property<bool>("Immobilizer");

                    b.Property<bool>("IsBrandNew");

                    b.Property<bool>("IsFirstOwner");

                    b.Property<bool>("IsMetalic");

                    b.Property<bool>("IsPearly");

                    b.Property<bool>("IsRegisteredInPoland");

                    b.Property<bool>("IsServicedInAuthorizedService");

                    b.Property<bool>("Isofix");

                    b.Property<bool>("KneesAirbag");

                    b.Property<bool>("LED");

                    b.Property<bool>("LaneAssistant");

                    b.Property<DateTime>("LayerDate");

                    b.Property<bool>("LeatherUpholstery");

                    b.Property<bool>("MP3");

                    b.Property<int>("Mileage");

                    b.Property<string>("Model");

                    b.Property<bool>("MultifunctionSteeringWheel");

                    b.Property<bool>("NotFactoryRadio");

                    b.Property<string>("OfferType");

                    b.Property<bool>("OnBoardComputer");

                    b.Property<bool>("PanoramicRoof");

                    b.Property<bool>("ParkingAssistant");

                    b.Property<bool>("ParkingHeater");

                    b.Property<bool>("PassengerAirbag");

                    b.Property<int>("PlacesCount");

                    b.Property<int>("Power");

                    b.Property<bool>("PowerSteering");

                    b.Property<bool>("RainSensor");

                    b.Property<bool>("RearParkingSensors");

                    b.Property<bool>("RearSideAirbags");

                    b.Property<string>("RegistrationNumber");

                    b.Property<bool>("ReversingCamera");

                    b.Property<bool>("RoofRails");

                    b.Property<bool>("SDCard");

                    b.Property<bool>("ShiftingPaddles");

                    b.Property<bool>("SpeedLimiter");

                    b.Property<bool>("StartStopSystem");

                    b.Property<bool>("SunRoof");

                    b.Property<bool>("TVTuner");

                    b.Property<bool>("TintedWindows");

                    b.Property<bool>("TractionControl");

                    b.Property<string>("TransmisionType");

                    b.Property<bool>("TwilightSensor");

                    b.Property<bool>("USBPort");

                    b.Property<string>("VIN");

                    b.Property<bool>("VelorUpholstery");

                    b.Property<bool>("XenonLights");

                    b.Property<int>("YearManufacture");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
